version: "3"

services:
    psql_db:
        env_file:
            - .env
        container_name: psql_db
        restart: always
        image: postgres
        environment:
            POSTGRES_INITDB_ARGS: --encoding=UTF-8
        ports:
            - "5432:5432"
        volumes:
            - ./psql:/var/lib/postgresql
