version: "3"

services:
    linkkky_waitlist_db:
        env_file:
            - .env
        container_name: linkkky_waitlist_db
        restart: always
        image: postgres
        environment:
            POSTGRES_INITDB_ARGS: --encoding=UTF-8
        ports:
            - "5432:5432"
