# Generated by Django 3.2.3 on 2021-05-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parkinglot',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('management_number', models.CharField(max_length=12)),
                ('parkinglot_name', models.CharField(max_length=26)),
                ('classification', models.CharField(max_length=2)),
                ('parkinglot_type', models.CharField(max_length=2)),
                ('road_name_address', models.CharField(blank=True, max_length=42, null=True)),
                ('number_address', models.CharField(blank=True, max_length=41, null=True)),
                ('parking_compartments_cnt', models.IntegerField()),
                ('level_division', models.CharField(max_length=2)),
                ('running_partial_division', models.CharField(max_length=3)),
                ('operating_days', models.CharField(max_length=26)),
                ('weekday_open_time', models.CharField(max_length=5)),
                ('weekday_close_time', models.CharField(max_length=5)),
                ('saturday_open_time', models.CharField(max_length=5)),
                ('saturday_close_time', models.CharField(max_length=5)),
                ('holiday_open_time', models.CharField(max_length=5)),
                ('holiday_close_time', models.CharField(max_length=5)),
                ('fee_info', models.CharField(max_length=2)),
                ('basic_parking_time', models.IntegerField()),
                ('basic_fee', models.IntegerField()),
                ('extra_time_unit', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('extra_fee', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('day_ticket_available_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('day_ticket_fee', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('monthly_ticket_fee', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=12, null=True)),
                ('special_things', models.CharField(blank=True, max_length=2090, null=True)),
                ('management_organization_name', models.CharField(max_length=22)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('longtitude', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
                ('data_last_updated', models.DateField()),
            ],
            options={
                'db_table': 'parkinglot',
                'managed': True,
            },
        ),
    ]
